mysql:
    driver:   Pdo_Mysql
    host:     mysql.crbn.intra
    port:     3306
    username: phpasm
    password: NWL6WM6hU9WMBAYY
    dbname:
        zabbix: zabbix
        glpi:   glpi
install:
    baseurl: /
debug:
    config: true
    sql: true
    route: true
    url: true