mysql:
    driver:   Pdo_Mysql
    host:     mysql.crbn.intra
    port:     3306
    username: phpasm
    password: NWL6WM6hU9WMBAYY
    dbname:
        zabbix: zabbix
        glpi:   glpi
install:
    baseurl: /
css:
    table:
        condensed: true
        bordered:  true
debug:
    config: false
    sql:    false
    route:  false
    url:    false