---
css:
  font: 0.850000
  table:
    condensed: true
    bordered: true
  zabbix:
    priority1: FFF2F2
    priority2: FFE0E0
    priority3: FFCECE
    priority4: FFBFBF
    priority5: F4F10B
    priority6: 4DF880
  glpi:
    priority1: FFF2F2
    priority2: FFE0E0
    priority3: FFCECE
    priority4: FFBFBF
    priority5: F4F10B
    priority6: F81CD6
html:
  home:
    title: ASM - Dashboard
  glpi:
    maxlentitle: "40"
  placeholder1: snmp
  placeholder2: zabbix
  placeholder3: badpasswd
  placeholder4: glpi
  placeholder5: glpi_due
  placeholder6: ~
db:
  zabbix:
    limit: "10"
  glpi:
    limit: "10"
    orderby: t.date_mod
js:
  zabbix:
    interval: "30"
  glpi:
    interval: "60"
  badpasswd:
    interval: "60"
host: "10255"
item: "76157"
...
